export { default as Facebook } from './logo-facebook.svg'
export { default as X } from './twitter-x.svg'
export { default as Tiktok } from './logo-tiktok.svg'
export { default as Instagram } from './logo-instagram.svg'
export { default as Linkedin } from './logo-linkedin.svg'
export { default as Youtube } from './logo-youtube.svg'